begin;

insert into cash_requests (
  request_id,
  request_date,
  group_name,
  plate_number,
  truck_type,
  driver_name,
  helper_name,
  logged_by,
  request_type,
  budget_type,
  amount,
  source,
  destination,
  remarks,
  deposit_needed,
  receiver_name,
  deposit_to,
  account_number,
  status,
  approval_status,
  payment_status,
  approved_by,
  approved_at,
  paid_by,
  paid_at,
  backup_status,
  backup_synced_at,
  backup_error,
  raw_data,
  created_at,
  updated_at,
  is_deleted
) values
  ('diesel_1778650870290_6vumzi', '2026-05-14'::date, null, 'ASDSA', null, null, null, 'ASDSA', 'Diesel PO', 'sad', 213, 'dasd', null, null, null, 'sadas', 'sadas', null, 'Draft', 'Draft', 'Unpaid', null, null, null, null, 'pending', null, null, '{"Record_ID":"","Message_Date":"","Message_Time":"","Encoded_At":"","Source_Platform":"","Sender":"ASDSA","Plate_Number":"ASDSA","Type":"","Person_Name":"sadas","Role":"","GCash_Number":"","Amount":213,"PO_Number":"sad","Liters":213,"Fuel_Station":"dasd","Route_Trip":"","Balance_After_Payroll":"","Source_Message":"","Review_Status":"Draft","Posted_Status":"","Payroll_Period_ID":"","Liquidation_Status":"","Duplicate_Key":"","Remarks":"","Created_By":"","Truck_Group":"","Client":"","Cash_ID":"diesel_1778650870290_6vumzi","Date":"2026-05-14T00:00:00.000Z","Time":"","Group_Category":"","Transaction_Type":"Diesel PO","Route":"","Encoded_By":"","Created_At":"2026-05-13T05:41:10.290Z","Updated_At":"2026-05-13T05:41:12.759Z","Logged_By":"","Deleted_At":"","Deleted_By":"","Is_Deleted":""}'::jsonb, '2026-05-13T05:41:10.290Z'::timestamptz, '2026-05-13T05:41:12.759Z'::timestamptz, false),
  ('diesel_1778656416936_fh2eb5', '2026-05-13'::date, null, 'NEWEWEW', null, null, null, 'NEWEWEW', 'Diesel PO', '23123', 123, 'sda', null, null, null, 'new', 'new', null, 'Draft', 'Draft', 'Unpaid', null, null, null, null, 'pending', null, null, '{"Record_ID":"","Message_Date":"","Message_Time":"","Encoded_At":"","Source_Platform":"","Sender":"NEWEWEW","Plate_Number":"NEWEWEW","Type":"","Person_Name":"new","Role":"","GCash_Number":"","Amount":123,"PO_Number":23123,"Liters":231,"Fuel_Station":"sda","Route_Trip":"","Balance_After_Payroll":"","Source_Message":"","Review_Status":"Draft","Posted_Status":"","Payroll_Period_ID":"","Liquidation_Status":"","Duplicate_Key":"","Remarks":"","Created_By":"","Truck_Group":"","Client":"","Cash_ID":"diesel_1778656416936_fh2eb5","Date":"2026-05-13T00:00:00.000Z","Time":"","Group_Category":"","Transaction_Type":"Diesel PO","Route":"","Encoded_By":"","Created_At":"2026-05-13T07:13:36.936Z","Updated_At":"2026-05-13T07:13:42.589Z","Logged_By":"","Deleted_At":"","Deleted_By":"","Is_Deleted":""}'::jsonb, '2026-05-13T07:13:36.936Z'::timestamptz, '2026-05-13T07:13:42.589Z'::timestamptz, false),
  ('diesel_1778919276356_nzyya4', '2026-05-17'::date, 'Bottle', 'ADJ1122', null, null, null, 'JR', 'Diesel PO', '123', 8000, 'trial', null, null, null, 'JR', 'JR', null, 'Draft', 'Approved', 'Unpaid', null, null, null, null, 'pending', null, null, '{"Record_ID":"","Message_Date":"","Message_Time":"","Encoded_At":"","Source_Platform":"","Sender":"ADJ1122","Plate_Number":"ADJ1122","Type":"","Person_Name":"JR","Role":"Logger","GCash_Number":"","Amount":8000,"PO_Number":123,"Liters":130,"Fuel_Station":"trial","Route_Trip":"","Balance_After_Payroll":"","Source_Message":"","Review_Status":"Approved","Posted_Status":"","Payroll_Period_ID":"","Liquidation_Status":"","Duplicate_Key":"","Remarks":"","Created_By":"","Truck_Group":"","Client":"","Cash_ID":"diesel_1778919276356_nzyya4","Date":"2026-05-17T00:00:00.000Z","Time":"","Group_Category":"Bottle","Transaction_Type":"Diesel PO","Route":"","Encoded_By":"JR","Created_At":"2026-05-16T09:22:30.644Z","Updated_At":"2026-05-17T05:15:16.271Z","Logged_By":"JR","Deleted_At":"","Deleted_By":"","Is_Deleted":""}'::jsonb, '2026-05-16T09:22:30.644Z'::timestamptz, '2026-05-17T05:15:16.271Z'::timestamptz, false),
  ('budget_1778919484680_x0l0id', '2026-05-17'::date, 'Bottle', 'CAD2629', null, null, null, 'gr', 'Trip Budget', 'Logger', 3233, null, 'MNL → SMY', null, null, 'gr', 'gr', null, 'Draft', 'Approved', 'Unpaid', null, null, null, null, 'pending', null, null, '{"Record_ID":"","Message_Date":"","Message_Time":"","Encoded_At":"","Source_Platform":"","Sender":"CAD2629","Plate_Number":"CAD2629","Type":"","Person_Name":"gr","Role":"Logger","GCash_Number":"","Amount":3233,"PO_Number":"","Liters":"","Fuel_Station":"","Route_Trip":"","Balance_After_Payroll":"","Source_Message":"","Review_Status":"Approved","Posted_Status":"","Payroll_Period_ID":"","Liquidation_Status":"","Duplicate_Key":"","Remarks":"","Created_By":"","Truck_Group":"","Client":"","Cash_ID":"budget_1778919484680_x0l0id","Date":"2026-05-17T00:00:00.000Z","Time":"","Group_Category":"Bottle","Transaction_Type":"Trip Budget","Route":"MNL → SMY","Encoded_By":"gr","Created_At":"2026-05-16T08:18:04.680Z","Updated_At":"2026-05-17T05:47:05.817Z","Logged_By":"gr","Deleted_At":"","Deleted_By":"","Is_Deleted":""}'::jsonb, '2026-05-16T08:18:04.680Z'::timestamptz, '2026-05-17T05:47:05.817Z'::timestamptz, false),
  ('bali_1778919537566_p3wbx0', '2026-05-16'::date, 'General / No Plate', null, null, null, null, null, 'Bali / Cash Advance', 'Mechanic', 5000, null, null, 'pambayad', null, 'mekanikoliko', 'mekanikoliko', null, 'Draft', 'For Approval', 'Unpaid', null, null, null, null, 'pending', null, null, '{"Record_ID":"","Message_Date":"","Message_Time":"","Encoded_At":"","Source_Platform":"","Sender":"","Plate_Number":"","Type":"","Person_Name":"mekanikoliko","Role":"Mechanic","GCash_Number":"","Amount":5000,"PO_Number":"","Liters":"","Fuel_Station":"","Route_Trip":"","Balance_After_Payroll":"","Source_Message":"","Review_Status":"For Approval","Posted_Status":"","Payroll_Period_ID":"","Liquidation_Status":"","Duplicate_Key":"","Remarks":"pambayad","Created_By":"","Truck_Group":"","Client":"","Cash_ID":"bali_1778919537566_p3wbx0","Date":"2026-05-16T00:00:00.000Z","Time":"","Group_Category":"General / No Plate","Transaction_Type":"Bali / Cash Advance","Route":"","Encoded_By":"","Created_At":"2026-05-16T08:18:57.566Z","Updated_At":"2026-05-16T08:20:37.467Z","Logged_By":"","Deleted_At":"","Deleted_By":"","Is_Deleted":""}'::jsonb, '2026-05-16T08:18:57.566Z'::timestamptz, '2026-05-16T08:20:37.467Z'::timestamptz, false),
  ('bali_1778919710419_uxu1j5', null, 'Bottle', 'CCM2159', null, null, null, 'dsa', 'Trip Budget', 'Logger', 2131231, null, null, 'asdsa', null, 'dsa', 'dsa', null, 'Draft', 'Draft', 'Unpaid', null, null, null, null, 'pending', null, null, '{"Record_ID":"","Message_Date":"","Message_Time":"","Encoded_At":"","Source_Platform":"","Sender":"CCM2159","Plate_Number":"CCM2159","Type":"","Person_Name":"dsa","Role":"Logger","GCash_Number":"","Amount":2131231,"PO_Number":"","Liters":"","Fuel_Station":"","Route_Trip":"","Balance_After_Payroll":"","Source_Message":"","Review_Status":"Draft","Posted_Status":"","Payroll_Period_ID":"","Liquidation_Status":"","Duplicate_Key":"","Remarks":"asdsa","Created_By":"","Truck_Group":"","Client":"","Cash_ID":"bali_1778919710419_uxu1j5","Date":"","Time":"","Group_Category":"Bottle","Transaction_Type":"Trip Budget","Route":"","Encoded_By":"dsa","Created_At":"","Updated_At":"2026-05-16T09:51:38.862Z","Logged_By":"dsa","Deleted_At":"2026-05-16T09:51:38.862Z","Deleted_By":"","Is_Deleted":true}'::jsonb, '2026-05-18T13:09:38.523Z'::timestamptz, '2026-05-16T09:51:38.862Z'::timestamptz, true),
  ('TEST_CASH_APPROVAL_20260517_001', '2026-05-17'::date, 'Bottle', 'TEST-APPROVAL', null, null, null, 'ChatGPT Test', 'Trip Budget', 'Logger', 1111, null, 'TEST Source → TEST Destination', 'TEST - safe to delete after notification test', null, 'Test Payee Approval', 'Test Payee Approval', null, 'Draft', 'For Approval', 'Unpaid', null, null, null, null, 'pending', null, null, '{"Record_ID":"TEST_CASH_APPROVAL_20260517_001","Message_Date":"","Message_Time":"","Encoded_At":"","Source_Platform":"Portal Test","Sender":"TEST BOT","Plate_Number":"TEST-APPROVAL","Type":"Trip Budget","Person_Name":"Test Payee Approval","Role":"Logger","GCash_Number":"","Amount":1111,"PO_Number":"","Liters":"","Fuel_Station":"","Route_Trip":"","Balance_After_Payroll":"","Source_Message":"TEST DATA - for approval notification routing","Review_Status":"For Approval","Posted_Status":"","Payroll_Period_ID":"","Liquidation_Status":"","Duplicate_Key":"","Remarks":"TEST - safe to delete after notification test","Created_By":"ChatGPT Test","Truck_Group":"","Client":"","Cash_ID":"TEST_CASH_APPROVAL_20260517_001","Date":"2026-05-17","Time":"","Group_Category":"Bottle","Transaction_Type":"Trip Budget","Route":"TEST Source → TEST Destination","Encoded_By":"ChatGPT Test","Created_At":"2026-05-17T06:10:00.000Z","Updated_At":"2026-05-17T06:10:00.000Z","Logged_By":"ChatGPT Test","Deleted_At":"","Deleted_By":"","Is_Deleted":""}'::jsonb, '2026-05-17T06:10:00.000Z'::timestamptz, '2026-05-17T06:10:00.000Z'::timestamptz, false),
  ('TEST_CASH_PAYMENT_20260517_001', '2026-05-17'::date, 'Bottle', 'TEST-PAYMENT', null, null, null, 'ChatGPT Test', 'Diesel PO', 'TEST-PO-001', 2222, 'TEST STATION', 'TEST Trial → TEST Yard', 'TEST - safe to delete after payment queue test', null, 'Test Payee Payment', 'Test Payee Payment', null, 'Draft', 'Approved', 'Unpaid', null, null, null, null, 'pending', null, null, '{"Record_ID":"TEST_CASH_PAYMENT_20260517_001","Message_Date":"","Message_Time":"","Encoded_At":"","Source_Platform":"Portal Test","Sender":"TEST BOT","Plate_Number":"TEST-PAYMENT","Type":"Diesel PO","Person_Name":"Test Payee Payment","Role":"Logger","GCash_Number":"","Amount":2222,"PO_Number":"TEST-PO-001","Liters":40,"Fuel_Station":"TEST STATION","Route_Trip":"","Balance_After_Payroll":"","Source_Message":"TEST DATA - approved payment queue routing","Review_Status":"Approved","Posted_Status":"","Payroll_Period_ID":"","Liquidation_Status":"","Duplicate_Key":"","Remarks":"TEST - safe to delete after payment queue test","Created_By":"ChatGPT Test","Truck_Group":"","Client":"","Cash_ID":"TEST_CASH_PAYMENT_20260517_001","Date":"2026-05-17","Time":"","Group_Category":"Bottle","Transaction_Type":"Diesel PO","Route":"TEST Trial → TEST Yard","Encoded_By":"ChatGPT Test","Created_At":"2026-05-17T06:10:00.000Z","Updated_At":"2026-05-17T06:10:00.000Z","Logged_By":"ChatGPT Test","Deleted_At":"","Deleted_By":"","Is_Deleted":""}'::jsonb, '2026-05-17T06:10:00.000Z'::timestamptz, '2026-05-17T06:10:00.000Z'::timestamptz, false)
on conflict (request_id) do update set
  request_date = excluded.request_date,
  group_name = excluded.group_name,
  plate_number = excluded.plate_number,
  truck_type = excluded.truck_type,
  driver_name = excluded.driver_name,
  helper_name = excluded.helper_name,
  logged_by = excluded.logged_by,
  request_type = excluded.request_type,
  budget_type = excluded.budget_type,
  amount = excluded.amount,
  source = excluded.source,
  destination = excluded.destination,
  remarks = excluded.remarks,
  deposit_needed = excluded.deposit_needed,
  receiver_name = excluded.receiver_name,
  deposit_to = excluded.deposit_to,
  account_number = excluded.account_number,
  status = excluded.status,
  approval_status = excluded.approval_status,
  payment_status = excluded.payment_status,
  approved_by = excluded.approved_by,
  approved_at = excluded.approved_at,
  paid_by = excluded.paid_by,
  paid_at = excluded.paid_at,
  backup_status = excluded.backup_status,
  backup_synced_at = excluded.backup_synced_at,
  backup_error = excluded.backup_error,
  raw_data = excluded.raw_data,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  is_deleted = excluded.is_deleted;

commit;
