-- Sample payroll rate matrix data for Payroll Trip Encoder testing.
-- Run after supabase/payroll-rate-matrix.sql.

insert into payroll_rate_matrix (
  rate_id,
  group_category,
  source,
  destination,
  truck_type,
  driver_salary,
  helper_salary,
  default_toll,
  default_passway,
  default_parking,
  default_lagay_loaded,
  default_lagay_empty,
  default_mano,
  default_allowance_driver,
  default_allowance_helper,
  default_other_expenses,
  active,
  remarks,
  updated_at
) values
(
  'RATE-2GO-PIER16-CALAMBA',
  '2GO',
  'PIER16',
  'CALAMBA',
  '',
  1400,
  700,
  938,
  0,
  0,
  400,
  280,
  150,
  400,
  300,
  900,
  true,
  'Sample 2GO route rate for testing',
  now()
),
(
  'RATE-2GO-PIER16-BATANGAS',
  '2GO',
  'PIER16',
  'BATANGAS',
  '',
  3600,
  1200,
  0,
  150,
  0,
  140,
  400,
  200,
  1000,
  750,
  200,
  true,
  'Sample 2GO route rate for testing',
  now()
)
on conflict (rate_id) do update set
  group_category = excluded.group_category,
  source = excluded.source,
  destination = excluded.destination,
  truck_type = excluded.truck_type,
  driver_salary = excluded.driver_salary,
  helper_salary = excluded.helper_salary,
  default_toll = excluded.default_toll,
  default_passway = excluded.default_passway,
  default_parking = excluded.default_parking,
  default_lagay_loaded = excluded.default_lagay_loaded,
  default_lagay_empty = excluded.default_lagay_empty,
  default_mano = excluded.default_mano,
  default_allowance_driver = excluded.default_allowance_driver,
  default_allowance_helper = excluded.default_allowance_helper,
  default_other_expenses = excluded.default_other_expenses,
  active = excluded.active,
  remarks = excluded.remarks,
  updated_at = now();
