begin;

insert into trucks (
  truck_id,
  plate_number,
  imei,
  truck_type,
  truck_make,
  body_type,
  trailer_plate,
  group_category,
  current_driver_id,
  current_helper_id,
  current_driver_name,
  current_helper_name,
  dispatcher,
  status,
  gps_source,
  last_known_latitude,
  last_known_longitude,
  last_gps_timestamp,
  odometer,
  orcr_status,
  insurance_expiry,
  registration_expiry,
  remarks,
  created_at,
  updated_at
) values
  ('TRK-NII3082', 'NII3082', null, null, null, 'FLAT BED 36PALLETS', 'NUB6094', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: FLAT BED 36PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-CCM7089', 'CCM7089', null, null, null, 'FLAT BED 34PALLETS', 'NUB1060', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: FLAT BED 34PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-NEG9655', 'NEG9655', null, null, null, 'PALLETIZED 34PALLETS', 'NUB1062', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: PALLETIZED 34PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-CDA1497', 'CDA1497', null, null, null, 'PALLETIZED 34PALLETS', 'NUB1016', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: PALLETIZED 34PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-CDI8153', 'CDI8153', null, null, null, 'FLAT BED 34PALLETS', 'NUB1018', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: FLAT BED 34PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-NBT6825', 'NBT6825', null, null, null, 'FLAT BED 32PALLETS', 'NUB6029', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: FLAT BED 32PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-CAL6557', 'CAL6557', null, null, null, 'FLAT BED 32PALLETS', '1301-982152', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: FLAT BED 32PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-CAD2629', 'CAD2629', null, null, null, 'PALLETIZED 32PALLETS', 'NUB6089', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: PALLETIZED 32PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-ADJ1241', 'ADJ1241', null, null, null, 'FLAT BED 32PALLETS', 'NUB1026', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: FLAT BED 32PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-CAD2631', 'CAD2631', null, null, null, 'PALLETIZED 32PALLETS', 'NUB6088', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: PALLETIZED 32PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-CAA5020', 'CAA5020', null, null, null, 'WINGVAN 28PALLETS', 'NUB6047', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: WINGVAN 28PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-NIU1171', 'NIU1171', null, null, null, 'FLAT BED 28PALLETS', 'NUB6097', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: FLAT BED 28PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-ADJ1122', 'ADJ1122', null, null, null, 'FLAT BED 28PALLETS', 'NUB6050', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: FLAT BED 28PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-CAL6559', 'CAL6559', null, null, null, 'WINGVAN 26PALLETS', 'NUB6039', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: WINGVAN 26PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-NBQ7400', 'NBQ7400', null, null, null, 'WINGVAN 26PALLETS', 'CUW994', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: WINGVAN 26PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-CCM4932', 'CCM4932', null, null, null, 'WINGVAN 26PALLETS', 'AUC2429', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: WINGVAN 26PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-NDQ4591', 'NDQ4591', null, null, null, 'FLAT BED 34PALLETS', 'NUB6095', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: FLAT BED 34PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz),
  ('TRK-NIH9288', 'NIH9288', null, null, null, 'FLAT BED 32PALLETS', 'NUB6020', 'Bottle', null, null, null, null, null, 'Active', null, null, null, null, null, null, null, null, 'Bottle source list: FLAT BED 32PALLETS. Verify tractor wheel class later if needed.', now()::timestamptz, now()::timestamptz)
on conflict (truck_id) do update set
  plate_number = excluded.plate_number,
  imei = excluded.imei,
  truck_type = excluded.truck_type,
  truck_make = excluded.truck_make,
  body_type = excluded.body_type,
  trailer_plate = excluded.trailer_plate,
  group_category = excluded.group_category,
  current_driver_id = excluded.current_driver_id,
  current_helper_id = excluded.current_helper_id,
  current_driver_name = excluded.current_driver_name,
  current_helper_name = excluded.current_helper_name,
  dispatcher = excluded.dispatcher,
  status = excluded.status,
  gps_source = excluded.gps_source,
  last_known_latitude = excluded.last_known_latitude,
  last_known_longitude = excluded.last_known_longitude,
  last_gps_timestamp = excluded.last_gps_timestamp,
  odometer = excluded.odometer,
  orcr_status = excluded.orcr_status,
  insurance_expiry = excluded.insurance_expiry,
  registration_expiry = excluded.registration_expiry,
  remarks = excluded.remarks,
  created_at = coalesce(trucks.created_at, excluded.created_at),
  updated_at = excluded.updated_at;

commit;
